### ISSUE TITLE
3.2 rc2 error when finalising installation

### ISSUE THREAD

**Issue by danboid** [oat-sa/tao-community#10]
I tried to install TAO community 3.2 rc2 under Ubuntu server 18.04 (php 7). I could get as far as the last screen of the installation wizard before getting this error:

```
[php7:error] [pid 1959] [client 192.168.122.1:42660] PHP Fatal error:  Cannot use oat\\taoQtiItem\\model\\qti\\Object as Object because 'Object' is a special class name in /var/www/html/taoplatform/taoQtiItem/model/qti/ParserFactory.php on line 54, referer: http://192.168.122.128/taoplatform/tao/install/
```

**Comment by jbout** [comment]
Tao 3.2 rc2 does not support PHP 7.2. Please use the latest develop branch https://github.com/oat-sa/tao-community/tree/release/sprint80 or downgrade your php version

**Comment by danboid** [comment]
I have opened a new ticket with a bit more info and using the latest git code here:

https://github.com/oat-sa/package-tao/issues/37
