### ISSUE TITLE
Question: distinguish the oat-sa/package-tao

### ISSUE THREAD

**Issue by davydov-vyacheslav** [oat-sa/tao-community#197]
Hi,

oat-sa/package-tao  package is using to build tao (e.g. via docker), but main files like composer.json are mostly updating there ...

So my questions are:
- is package-tao still alive?
- is tao-community is a replacement of package-tao?
- are we (end user) able to use package-tao with tao-community files?

Thanks,
Slava

**Comment by FrankVan1982** [comment]
`tao-community` is a component of `package-tao`. So, if you are installing `package-tao`, 98% of packages downloaded with Composer come from `tao-community`.

**Comment by FrankVan1982** [comment]
1) Yes.
2) No.
3) Obviously.

**Comment by davydov-vyacheslav** [comment]
thank you
